[package]
name = "secret-toolkit-viewing-key"
version = "0.6.0"
edition = "2018"
authors = ["SCRT Labs <info@scrtlabs.com>"]
license-file = "../../LICENSE"
repository = "https://github.com/scrtlabs/secret-toolkit"
readme = "Readme.md"
description = "Boilerplate for using viewing keys in Secret Contracts"
categories = ["cryptography::cryptocurrencies", "wasm"]
keywords = ["secret-network", "secret-contracts", "secret-toolkit"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
serde = "1.0"
schemars = "0.7"
base64 = "0.11.0" # Same as used by cosmwas-std
subtle = { version = "2.2.3", default-features = false }
cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", branch = "secret" , features=["staking"], package ="secret-cosmwasm-std" }
cosmwasm-storage = { package = "secret-cosmwasm-storage", version = "1.0.0" }
secret-toolkit-crypto = { version = "0.6", path = "../crypto", default-features = false, features = [
    "hash",
    "rand",
] }
secret-toolkit-utils = { version = "0.6", path = "../utils" }
