[package]
name = "secret-toolkit-permit"
version = "0.6.0"
edition = "2018"
authors = ["SCRT Labs <info@scrtlabs.com>"]
license-file = "../../LICENSE"
repository = "https://github.com/scrtlabs/secret-toolkit"
readme = "Readme.md"
description = "Boilerplate for using permits in Secret Contracts"
categories = ["cryptography::cryptocurrencies", "wasm"]
keywords = ["secret-network", "secret-contracts", "secret-toolkit"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", branch = "secret" , features=["staking"], package ="secret-cosmwasm-std" }
serde = "1.0"
ripemd160 = { version = "0.9.1", default-features = false }
schemars = "0.8.1"
bech32 = "0.8.1"
remain = "0.2.2"
secret-toolkit-crypto = { version = "0.6.0", path = "../crypto", features = [
    "hash",
] }
