[package]
name = "secret-toolkit-serialization"
version = "0.6.0"
edition = "2018"
authors = ["SCRT Labs <info@scrtlabs.com>"]
license-file = "../../LICENSE"
repository = "https://github.com/scrtlabs/secret-toolkit"
readme = "Readme.md"
description = "Helper types for serialization in Secret Contracts"
categories = ["cryptography::cryptocurrencies", "wasm"]
keywords = ["secret-network", "secret-contracts", "secret-toolkit"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["json", "bincode2", "base64"]
json = []
base64 = ["schemars"]

[dependencies]
serde = "1.0"
bincode2 = { version = "2.0", optional = true }
schemars = { version = "0.8.1", optional = true }
cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", branch = "secret" , features=["staking"], package ="secret-cosmwasm-std" }

[dev-dependencies]
serde_json = "1"
cosmwasm-schema = { version = "1.0" }
